[tool.poetry]
name = "ep-202406-leern-flask"
version = "0.1.0"
description = ""
authors = ["Eugenii Petrov <p174@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.2"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
